# brownie syntax to declare dependencies and pull directly from sources
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2 
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
compiler:
  solc:
    ##this is how our solidity compiler knows to remap dependency and pull from github
    remappings: 
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2'